### Read all user(request to a protected route)
GET http://localhost:4000/user-api/users
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhdmlAbWFpbC5jb20iLCJpYXQiOjE3NzI4NzY0NzgsImV4cCI6MTc3Mjg4MDA3OH0.WpmikNCFP3J9KKU_l5_ic4rhmlmL2er7Q2RxKdL_tkY; Path=/; HttpOnly; SameSite=Lax


### Read user by id
GET http://localhost:4000/user-api/users/69aa70cb4e92389dc6da058
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhdmlAbWFpbC5jb20iLCJpYXQiOjE3NzI4NzY0NzgsImV4cCI6MTc3Mjg4MDA3OH0.WpmikNCFP3J9KKU_l5_ic4rhmlmL2er7Q2RxKdL_tkY; Path=/; HttpOnly; SameSite=Lax



### Create new User
POST http://localhost:4000/user-api/users
Content-Type: application/json

{
    "username":"kiran",
    "password":"kiran",
    "email":"kiran@mail.com",
    "age":20
}


### Update existing user
PUT http://localhost:4000/user-api/users/69abbdf38d8f4e28df6f2d33
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhdmlAbWFpbC5jb20iLCJpYXQiOjE3NzI4NzY0NzgsImV4cCI6MTc3Mjg4MDA3OH0.WpmikNCFP3J9KKU_l5_ic4rhmlmL2er7Q2RxKdL_tkY; Path=/; HttpOnly; SameSite=Lax
Content-Type: application/json

{
    "username":"ravi",
    "password":"ravi",
    "email":"ravi@mail.com",
    "age":20
}


### User Login
POST http://localhost:4000/user-api/auth
Content-Type:application/json

{
    "email":"ravi@mail.com",
    "password":"ravi"
}

### Delete user by id
DELETE http://localhost:4000/user-api/users/69aa8a4c5aff9ed7001e4af1
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhdmlAbWFpbC5jb20iLCJpYXQiOjE3NzI4NzY0NzgsImV4cCI6MTc3Mjg4MDA3OH0.WpmikNCFP3J9KKU_l5_ic4rhmlmL2er7Q2RxKdL_tkY; Path=/; HttpOnly; SameSite=Lax




### Product API

### Read all products
GET http://localhost:4000/product-api/products




###Real product by brand
GET http://localhost:4000/product-api/products/5



### Create new Product
POST http://localhost:4000/product-api/products
Content-Type: application/json

{
    "productId":5,
    "productName":"Watch",
    "price":10000,
    "brand":"Z"
}

### Modify existing product
PUT http://localhost:4000/product-api/products/1
Content-Type: application/json

{
    "productId":5,
    "productName":"Watch",
    "price":12000,
    "brand":"Z"
}


### get product cookie
POST http://localhost:4000/product-api/auth
Content-Type:application/json

{
    "productId":2,
}

### Delete a product
DELETE http://localhost:4000/product-api/products/5